"""
Shared pytest fixtures for Arnold characterization tests.

Loads the stored golden fixtures (tests/golden/goldens.json + goldens.npz)
generated by tests/golden/generate_goldens.py.
"""

import os
import sys
import json

import torch
import pytest
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)  # make tests/helpers.py importable

GOLDEN_JSON = os.path.join(HERE, "golden", "goldens.json")
GOLDEN_NPZ = os.path.join(HERE, "golden", "goldens.npz")


########################################
#               Fixtures               #
########################################


@pytest.fixture(scope="session")
def goldens():
    with open(GOLDEN_JSON) as f:
        return json.load(f)


@pytest.fixture(scope="session")
def goldens_npz():
    return dict(np.load(GOLDEN_NPZ))


@pytest.fixture(autouse=True)
def _deterministic():
    """Keep torch deterministic and CPU-only for every test."""
    torch.manual_seed(0)
    torch.use_deterministic_algorithms(False)
    yield  # noqa: PT022
