"""
Shared pytest fixtures for MyoTrainer characterization tests.

Loads the stored golden fixtures (tests/golden/goldens.json + goldens.npz)
generated by tests/golden/generate_goldens.py.
"""

import os
import sys
import json

import torch
import pytest
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)  # make tests/helpers.py importable

GOLDEN_JSON = os.path.join(HERE, "golden", "goldens.json")
GOLDEN_NPZ = os.path.join(HERE, "golden", "goldens.npz")


########################################
#           Two-stage gating           #
########################################

# Stage 1 (default): fast, CPU-only, deterministic — runs everywhere.
# Stage 2: heavy / accelerator tests marked `@pytest.mark.stage2`; run only
# when a GPU/MPS accelerator is present, or when forced with RUN_STAGE2=1.


def _accelerator_available() -> bool:
    if torch.cuda.is_available():
        return True
    mps = getattr(torch.backends, "mps", None)
    return bool(mps is not None and mps.is_available())


def _stage2_enabled() -> bool:
    return os.environ.get("RUN_STAGE2") == "1" or _accelerator_available()


def pytest_configure(config):
    config.addinivalue_line(
        "markers",
        "stage2: heavy/accelerator test; runs only when a GPU/MPS device is "
        "present or RUN_STAGE2=1",
    )


def pytest_collection_modifyitems(config, items):
    if _stage2_enabled():
        return
    skip = pytest.mark.skip(
        reason="stage-2 test (needs a GPU/MPS device or RUN_STAGE2=1)",
    )
    for item in items:
        if "stage2" in item.keywords:
            item.add_marker(skip)


########################################
#               Fixtures               #
########################################


@pytest.fixture(scope="session")
def goldens():
    with open(GOLDEN_JSON) as f:
        return json.load(f)


@pytest.fixture(scope="session")
def goldens_npz():
    return dict(np.load(GOLDEN_NPZ))


@pytest.fixture(autouse=True)
def _deterministic():
    """Keep torch deterministic and CPU-only for every test."""
    torch.manual_seed(0)
    torch.use_deterministic_algorithms(False)
    yield  # noqa: PT022
